version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: fcm-django
    versions:
    - 0.3.7
    - 0.3.8
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  - dependency-name: boto3
    versions:
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.2
    - 1.17.3
    - 1.17.4
    - 1.17.5
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: django-bootstrap4
    versions:
    - 2.3.1
  commit-message:
    prefix: Crowdbotics
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 2.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-native-keyboard-aware-scroll-view
    versions:
    - 0.9.3
  - dependency-name: react-native
    versions:
    - 0.62.2
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: react-test-renderer
    versions:
    - 16.13.0
  commit-message:
    prefix: Crowdbotics
